server:
   port: 8080 #tomcat启动端口
   tomcat:
      uri-encoding: UTF-8 #tomcat编码
   servlet:
      context-path: null
spring:
   datasource:
      url: jdbc:mysql://192.168.0.198:3306/test
      username: root
      password: 123456
      driver-class-name: org.mariadb.jdbc.Driver
   thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      mode: HTML
      cache: false
   devtools:
      restart:
         enabled: false
mybatis:
   mapper-locations: classpath:/mapper/*.xml
   type-aliases-package: com.web.entity